import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
const runtimeNodeModules = process.env.RUNTIME_NODE_MODULES;
if (!path.isAbsolute(runtimeNodeModules ?? "")) {
  throw new Error("RUNTIME_NODE_MODULES must be an absolute path");
}
const { Presentation, PresentationFile } = await import(pathToFileURL(
  path.join(runtimeNodeModules, "@oai/artifact-tool/dist/artifact_tool.mjs"),
).href);

const workspaceDir = process.env.WORKSPACE_DIR ?? process.cwd();
const tmpDir = path.join(workspaceDir, "tmp/presentation");
const publicationDir = process.env.PUBLICATION_DIR ?? path.resolve(import.meta.dirname, "..");
const skillDir = process.env.SKILL_DIR;
if (!path.isAbsolute(workspaceDir) || !path.isAbsolute(publicationDir) || !path.isAbsolute(skillDir ?? "")) {
  throw new Error("WORKSPACE_DIR, PUBLICATION_DIR and SKILL_DIR must be absolute paths");
}
const { resolvePresentationFont } = await import(pathToFileURL(
  path.join(skillDir, "container_tools/artifact_tool_utils.mjs"),
).href);

await fs.mkdir(tmpDir, { recursive: true });
const font = resolvePresentationFont({ fontFamily: "DejaVu Sans" });
const deck = Presentation.create({ slideSize: { width: 1280, height: 720 } });

const C = {
  navy: "#12324A", blue: "#2C6E9F", paleBlue: "#E9F3F9", teal: "#087E8B",
  paleTeal: "#E5F5F3", amber: "#D98916", paleAmber: "#FFF3DD", gray: "#61717D",
  paleGray: "#F3F6F8", ink: "#182B3A", white: "#FFFFFF", line: "#B9C7D1",
  red: "#9E3C35", paleRed: "#F9ECEA",
};
const SRC = {
  overview: "Series source: https://ai.jessepike.dev/ | NIST Cyber AI Profile: https://www.nccoe.nist.gov/projects/cyber-ai-profile",
  a1: "Architecture 01: https://ai.jessepike.dev/architectures/01-secure-business-ai | Guide: https://ai.jessepike.dev/guides/01-secure-business-ai-guide | OWASP Agentic Applications: https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/ | NCSC agentic AI guidance: https://www.ncsc.gov.uk/blogs/managing-the-cyber-risk-of-agentic-ai",
  a2: "Architecture 02: https://ai.jessepike.dev/architectures/02-defend-against-ai | Guide: https://ai.jessepike.dev/guides/02-defend-against-ai-guide | MITRE ATT&CK: https://attack.mitre.org/ | MITRE ATLAS: https://atlas.mitre.org/ | CISA phishing-resistant MFA: https://www.cisa.gov/sites/default/files/2023-01/fact-sheet-implementing-phishing-resistant-mfa-508c.pdf",
  a3: "Architecture 03: https://ai.jessepike.dev/architectures/03-defend-with-ai | Guide: https://ai.jessepike.dev/guides/03-defend-with-ai-guide | NCSC Cyber Shield: https://www.ncsc.gov.uk/blogs/cyber-shield-the-path-to-an-agentic-ai-future-for-cyber-defence | OWASP GenAI LLM Top 10: https://genai.owasp.org/resource/owasp-genai-llm-top-10-2026/",
  gov: "AI Governance: https://ai.jessepike.dev/architectures/04-ai-governance | Guide: https://ai.jessepike.dev/guides/04-ai-governance-guide | NIST AI RMF Core: https://airc.nist.gov/airmf-resources/airmf/5-sec-core/ | NIST trustworthiness characteristics: https://airc.nist.gov/airmf-resources/airmf/3-sec-characteristics/ | ISO/IEC 42001 overview: https://www.iso.org/standard/42001",
  review: "Review status: https://ai.jessepike.dev/review-status | Model-assisted review summary: Fable 5.1",
  standard: "Series authoring standard: https://ai.jessepike.dev/authoring-standard",
};
const reviewNote = "Presentation-wide status: Proposed discussion draft. The three original packages received discussion-level review with material reservations; the review raised 30 findings, and substantive design questions remain open. The revised overview and AI Governance companion received bounded model-assisted review; human review remains open. No slide asserts deployment approval, certification, or demonstrated effectiveness.";

function shape(slide, geometry, pos, fill = "none", line = "none") {
  return slide.shapes.add({ geometry, position: pos, fill, line: { fill: line, width: line === "none" ? 0 : 1 } });
}
function text(slide, content, pos, style = {}) {
  const box = shape(slide, "textbox", pos);
  box.text = content;
  box.text.style = { typeface: font, fontSize: 20, color: C.ink, autoFit: "none", ...style };
  return box;
}
function heading(slide, title, eyebrow = "AI SECURITY REFERENCE ARCHITECTURES") {
  text(slide, eyebrow, { left: 64, top: 32, width: 870, height: 22 }, { fontSize: 12, bold: true, color: C.teal });
  text(slide, title, { left: 64, top: 62, width: 1080, height: 62 }, { fontSize: 34, bold: true, color: C.navy });
  shape(slide, "rect", { left: 64, top: 132, width: 1152, height: 2 }, C.line);
}
function footer(slide, number) {
  text(slide, "Proposed discussion draft  |  Conceptual reference architecture", { left: 64, top: 684, width: 900, height: 18 }, { fontSize: 10, color: C.gray });
  text(slide, String(number).padStart(2, "0"), { left: 1154, top: 680, width: 62, height: 20 }, { fontSize: 12, bold: true, color: C.gray });
}
function notes(slide, body, sources) {
  slide.speakerNotes.textFrame.setText(`${reviewNote}\n\n${body}\n\nSources: ${sources}`);
  slide.speakerNotes.setVisible(true);
}
function card(slide, title, body, pos, color = C.blue, opts = {}) {
  shape(slide, "roundRect", pos, opts.fill ?? C.white, opts.line ?? C.line);
  shape(slide, "rect", { left: pos.left, top: pos.top, width: 7, height: pos.height }, color);
  text(slide, title, { left: pos.left + 24, top: pos.top + 18, width: pos.width - 42, height: 58 }, { fontSize: opts.titleSize ?? 21, bold: true, color });
  text(slide, body, { left: pos.left + 24, top: pos.top + 90, width: pos.width - 42, height: pos.height - 106 }, { fontSize: opts.bodySize ?? 19, color: C.ink });
}
function band(slide, label, detail, top, color = C.navy) {
  shape(slide, "roundRect", { left: 64, top, width: 1152, height: 58 }, color);
  text(slide, label, { left: 88, top: top + 14, width: 230, height: 28 }, { fontSize: 19, bold: true, color: C.white });
  text(slide, detail, { left: 334, top: top + 16, width: 850, height: 25 }, { fontSize: 16, color: C.white });
}
function flow(slide, steps, top, opts = {}) {
  const left = opts.left ?? 76; const width = opts.width ?? 1120; const gap = opts.gap ?? 18;
  const height = Math.max(opts.height ?? 122, 210);
  const w = (width - gap * (steps.length - 1)) / steps.length;
  steps.forEach((step, i) => {
    const x = left + i * (w + gap);
    shape(slide, "roundRect", { left: x, top, width: w, height }, step.fill ?? C.paleBlue, step.color ?? C.blue);
    text(slide, step.title, { left: x + 14, top: top + 16, width: w - 28, height: 50 }, { fontSize: 17, bold: true, color: step.color ?? C.navy });
    text(slide, step.body, { left: x + 14, top: top + 76, width: w - 28, height: height - 92 }, { fontSize: step.bodySize ?? opts.bodySize ?? 18, color: C.ink });
    if (i < steps.length - 1) {
      const a = shape(slide, "rightArrow", { left: x + w + 2, top: top + (height / 2) - 12, width: gap - 4, height: 24 }, C.gray);
      a.text = "";
    }
  });
}
function question(slide, label, value, y, color = C.blue) {
  text(slide, label, { left: 98, top: y, width: 270, height: 24 }, { fontSize: 15, bold: true, color });
  text(slide, value, { left: 388, top: y - 2, width: 720, height: 44 }, { fontSize: 18, color: C.ink });
  shape(slide, "rect", { left: 98, top: y + 49, width: 1010, height: 1 }, C.line);
}
async function addPng(slide, filename, alt, pos) {
  const blob = await fs.readFile(path.join(publicationDir, "public/images", filename));
  slide.images.add({ blob, contentType: "image/png", alt, fit: "contain", position: pos });
}

const slides = [];
function add(build) { slides.push(build); }

add(async (s, n) => {
  shape(s, "rect", { left: 0, top: 0, width: 1280, height: 720 }, C.navy);
  shape(s, "rect", { left: 0, top: 0, width: 28, height: 720 }, C.teal);
  text(s, "AI Security\nReference Architectures", { left: 86, top: 164, width: 820, height: 150 }, { fontSize: 48, bold: true, color: C.white });
  text(s, "A proposed series for discussing how AI changes what we protect, how we are attacked, and how we defend", { left: 92, top: 344, width: 770, height: 80 }, { fontSize: 24, color: "#D9E8F1" });
  text(s, "Conceptual reference  |  Version 0.1  |  9 September 2026", { left: 92, top: 558, width: 730, height: 28 }, { fontSize: 16, color: "#A9C6D9" });
  notes(s, "Open by framing this as a teaching and architecture-discussion package. The deck makes proposed responsibilities and questions visible. It does not select products or approve an implementation.", `${SRC.overview}; ${SRC.standard}`);
});
add(async (s, n) => { heading(s, "How to use this deck"); flow(s, [
  { title: "Situation and decision", body: "Start with a real use, consequence, owner and next decision." },
  { title: "Arrival and oversight", body: "Ask how AI arrived and whether it is inside normal oversight." },
  { title: "Governance and security", body: "Connect decision rights and evidence to the relevant security views." },
  { title: "Design evidence", body: "Define authority, interfaces, tests and recovery before deployment." },
], 220, { height: 150 });
  text(s, "Use the supplier-payment example to see one event through governance and all three security views. Open the detailed guides when a box, connector or decision needs a more technical explanation.", { left: 92, top: 474, width: 1040, height: 62 }, { fontSize: 22, color: C.ink }); footer(s,n); notes(s, "Use this sequence to avoid starting with products or unexplained AI terms. The deck connects the introductory decision conversation with the later architecture detail.", `${SRC.standard}; ${SRC.gov}`); });
add(async (s,n) => { heading(s,"Scope and status"); card(s,"What this is","A proposed security reference series with an AI Governance companion for connected architecture discussion.",{left:82,top:190,width:510,height:176},C.navy,{fill:C.paleBlue}); card(s,"What this is not","A deployment blueprint, product selection, independent certification, or acceptance decision.",{left:688,top:190,width:510,height:176},C.amber,{fill:C.paleAmber}); band(s,"Status","Revised overview and governance: bounded model review. Human review open.",452,C.gray); footer(s,n); notes(s,"Pause here to keep the authority boundary clear. Readers can use the package to prepare choices and tests, but a real enterprise still needs owners, systems, requirements and acceptance evidence. The revised overview and governance companion received bounded model-assisted review; human review remains open.",`${SRC.overview}; ${SRC.gov}; ${SRC.review}`); });
add(async (s,n) => { heading(s,"Start with the situation and next decision"); flow(s,[{title:"Real situation",body:"Name the AI use, affected people, data, actions and business consequence."},{title:"Accountable owner",body:"Identify who answers for the outcome and which specialists hold related decisions."},{title:"Decision pending",body:"State what must be decided now, with what evidence and authority."},{title:"Valid outcome",body:"Proceed, add conditions, pause, narrow, redesign or stop."}],212,{height:160}); footer(s,n); notes(s,"Begin with a real situation, not a product category. Ownership follows the decision and consequence: a business owner commonly answers for the business outcome, while security and other functions decide within their assigned authority.",`${SRC.overview}; ${SRC.gov}`); });
add(async (s,n) => { heading(s,"Workstream and architecture view"); card(s,"Workstream","The primary motion selected for the current decision. It routes the work and makes the next owner and choice clear.",{left:92,top:210,width:470,height:250},C.navy,{fill:C.paleGray}); card(s,"Architecture view","A perspective used to design the protections. Several views can apply to one situation without creating duplicate work.",{left:710,top:210,width:470,height:250},C.blue,{fill:C.paleBlue}); text(s,"For one supplier-payment change, a business workstream may own the decision while every relevant security view informs the design.",{left:94,top:532,width:1030,height:40},{fontSize:20,bold:true,color:C.teal}); footer(s,n); notes(s,"Use this distinction to prevent a reader from treating the three security perspectives as a queue or organization chart. A motion selects the current work; an architecture view makes particular safeguards visible.",SRC.overview); });
add(async (s,n) => { heading(s,"How AI arrives: four overlapping questions"); card(s,"Built","Was it developed or assembled by the organization?",{left:76,top:210,width:256,height:220},C.blue,{fill:C.paleBlue,bodySize:18}); card(s,"Bought","Is it supplied as a service or purchased product?",{left:364,top:210,width:256,height:220},C.teal,{fill:C.paleTeal,bodySize:18}); card(s,"Embedded","Does an existing product contain an AI feature?",{left:652,top:210,width:256,height:220},C.navy,{fill:C.paleGray,bodySize:18}); card(s,"Unmanaged","Has the use not entered normal oversight?",{left:940,top:210,width:256,height:220},C.amber,{fill:C.paleAmber,bodySize:18}); text(s,"Ask every question. A bought product may have embedded AI, and any built, bought or embedded use may be unmanaged.",{left:92,top:500,width:1070,height:42},{fontSize:20,bold:true,color:C.navy}); footer(s,n); notes(s,"These are discovery prompts, not mutually exclusive inventory categories. The purpose is to find the real use and oversight gap before assigning a route or control response.",`${SRC.overview}; ${SRC.gov}`); });
add(async (s,n) => { heading(s,"Permitted data use needs two decisions"); card(s,"Access","May this identity reach the data?\n\nSecurity controls identity, resource, operation, destination and retention.",{left:92,top:205,width:470,height:260},C.blue,{fill:C.paleBlue}); card(s,"Appropriate use","May this data be used for this purpose, with adequate evidence and obligations to affected people?",{left:710,top:205,width:470,height:260},C.teal,{fill:C.paleTeal}); text(s,"Access alone does not establish appropriate use. Missing evidence can justify a pause, narrower conditions, redesign or stopping.",{left:92,top:530,width:1080,height:40},{fontSize:20,bold:true,color:C.navy}); footer(s,n); notes(s,"Security access enforcement remains necessary. Governance adds the purpose and suitability question: whether the proposed data use is allowed and appropriate for the context. Neither answer substitutes for the other.",`${SRC.overview}; ${SRC.gov}`); });
add(async (s,n) => { heading(s,"AI governance and AI security"); card(s,"AI governance","Direct and oversee AI use: decision rights, acceptable uses and risks, required evidence, and reassessment.",{left:76,top:200,width:500,height:276},C.teal,{fill:C.paleTeal}); card(s,"AI security","Protect AI systems and reached resources, withstand AI-enabled attacks, and use AI safely in security work.",{left:704,top:200,width:500,height:276},C.blue,{fill:C.paleBlue}); text(s,"Governance connects to the three peer security views. It is an overarching discipline, not a fourth security category.",{left:92,top:536,width:1080,height:38},{fontSize:20,bold:true,color:C.navy}); footer(s,n); notes(s,"Governance includes security requirements and extends to appropriate purpose, reliability, safety, privacy, fairness, transparency, and effects on people and business. A system can meet access rules and still be unsuitable or harmful.",SRC.gov); });
add(async (s,n) => { heading(s,"AI governance: six connected responsibilities"); card(s,"Purpose and ownership","What is it for, who is affected, and who answers for it?",{left:72,top:174,width:352,height:194},C.blue,{fill:C.paleBlue,bodySize:17}); card(s,"Risk and impact review","What could go wrong, and which obligations apply?",{left:464,top:174,width:352,height:194},C.teal,{fill:C.paleTeal,bodySize:17}); card(s,"Decision and conditions","May it proceed, with what limits and evidence?",{left:856,top:174,width:352,height:194},C.navy,{fill:C.paleGray,bodySize:17}); card(s,"Implementation and release","Have conditions been implemented and tested?",{left:72,top:406,width:352,height:194},C.blue,{fill:C.paleBlue,bodySize:17}); card(s,"Operation and reassessment","Are performance, impacts and conditions still acceptable?",{left:464,top:406,width:352,height:194},C.teal,{fill:C.paleTeal,bodySize:17}); card(s,"Change or retirement","What requires reapproval, restriction, redesign or stopping?",{left:856,top:406,width:352,height:194},C.navy,{fill:C.paleGray,bodySize:17}); footer(s,n); notes(s,"These responsibilities are connected and may be revisited. Decision rights, policy and escalation apply throughout. Existing business, product, procurement, privacy, security, change, incident and assurance processes should perform the responsibilities where they can.",SRC.gov); });
add(async (s,n) => { heading(s,"AI Governance","ORIGINAL REFERENCE VISUAL"); await addPng(s,"04-ai-governance.png","AI Governance reference architecture",{left:154,top:154,width:972,height:510}); footer(s,n); notes(s,"Read the top band, six responsibilities and their evidence handoffs, then the feedback loop, risk domains and security interface. Connector labels carry records or decisions; they do not transfer accountability automatically. The revised overview and governance companion received bounded model-assisted review; human review remains open.",`${SRC.gov}; ${SRC.review}; 04-ai-governance.png`); });
add(async (s,n) => { heading(s,"AI security"); text(s,"AI security protects the organization as AI becomes part of its work, attackers’ methods, and its defenses.",{left:98,top:202,width:1030,height:95},{fontSize:31,bold:true,color:C.navy}); text(s,"The organizing idea: AI changes what we protect, how we are attacked, and how we defend.",{left:98,top:344,width:970,height:60},{fontSize:25,color:C.teal}); text(s,"The series takes a cybersecurity view. Business quality, privacy, safety and wider AI governance still matter, but they are not claimed as covered here.",{left:98,top:464,width:970,height:55},{fontSize:20,color:C.ink}); footer(s,n); notes(s,"Introduce an AI agent in ordinary terms: an AI-based workflow that can use tools to carry out parts of a task. It has no independent business authority or human accountability.",SRC.overview); });
add(async (s,n) => { heading(s,"Three views of one security program"); card(s,"01  Secure business AI","What may our AI access and do?\n\nBuilds on application security, data protection and access control.",{left:72,top:194,width:352,height:260},C.blue,{fill:C.paleBlue}); card(s,"02  Defend against AI","How do we stop AI-enabled attacks?\n\nBuilds on fraud prevention, detection and incident response.",{left:464,top:194,width:352,height:260},C.amber,{fill:C.paleAmber}); card(s,"03  Defend with AI","How can AI help security act within limits?\n\nBuilds on investigation, playbooks and controlled automation.",{left:856,top:194,width:352,height:260},C.teal,{fill:C.paleTeal}); text(s,"These are peer perspectives. They overlap during real business events and do not form a maturity sequence.",{left:92,top:532,width:1030,height:36},{fontSize:21,bold:true,color:C.navy}); footer(s,n); notes(s,"Each architecture answers a different question about the same security program. Repeated capabilities across views require explicit interfaces and ownership; they are not duplicate products or teams.",SRC.overview); });
add(async (s,n) => { heading(s,"Shared foundation"); band(s,"Ownership","Purpose, consequence, exception and change decisions need accountable people.",190,C.navy); band(s,"Access rules","People, applications and AI workflows receive task-appropriate permissions.",272,C.blue); band(s,"Data protection","Sensitivity, origin, permitted destinations and retention shape use.",354,C.teal); band(s,"Evidence","Records from source systems reconstruct decisions and check outcomes.",436,C.gray); band(s,"Recovery","People can stop, contain and restore. Recovery actions have their own authority.",518,C.navy); footer(s,n); notes(s,"Call out that these are common concerns rather than a centrally prescribed platform. The detailed implementation must assign real owners, systems and measurable acceptance conditions.",SRC.overview); });
add(async (s,n) => { heading(s,"Series overview","ORIGINAL REFERENCE VISUAL"); await addPng(s,"00-ai-security.png","Overview of the three AI security reference architectures",{left:188,top:156,width:904,height:500}); footer(s,n); notes(s,"Use this visual as an orientation map. Its relationship arrows mean responsibility dependencies, not network traffic, access rights, central ownership or automatic response.",`${SRC.overview}; 00-ai-security.png`); });
add(async (s,n) => { heading(s,"A familiar example: supplier payment change"); flow(s,[{title:"Supplier request",body:"A supplier asks to change bank details."},{title:"Business assistant",body:"Reads the request and prepares a proposed change."},{title:"Decision point",body:"A person or rule checks the actual target, scope and authority."},{title:"Payment outcome",body:"The company pays the right supplier and records what occurred."}],212,{height:148}); text(s,"The recurring example is illustrative. It names no company, system or approved procedure.",{left:90,top:486,width:860,height:32},{fontSize:19,color:C.gray}); footer(s,n); notes(s,"Keep the business outcome fixed across all three views: pay the right supplier and keep the business running. The views reveal different protections and decisions around that goal.",SRC.overview); });
add(async (s,n) => { heading(s,"01. Secure business AI"); text(s,"Question: What may our AI access and do?",{left:94,top:205,width:1000,height:50},{fontSize:31,bold:true,color:C.navy}); text(s,"An AI workflow can interpret documents and generate tool requests. It must not turn untrusted content or its own output into permission.",{left:94,top:300,width:1010,height:58},{fontSize:22,color:C.ink}); band(s,"Design focus","Limit data access and actions. Bind authority to the initiator, task and current policy.",450,C.blue); footer(s,n); notes(s,"The familiar anchor is application security and access control. The AI-specific concern is that a workflow can reason over untrusted content and propose actions, so its output needs separate enforcement.",SRC.a1); });
add(async (s,n) => { heading(s,"Secure business AI","ORIGINAL REFERENCE VISUAL"); await addPng(s,"01-secure-business-ai.png","Secure business AI reference architecture",{left:154,top:154,width:972,height:510}); footer(s,n); notes(s,"Read from request through scoped task, restricted runtime, enforcement and resources. The bands are cross-cutting responsibilities, not a sequence. The dashed box marks the agent runtime boundary; enforcement remains outside it.",`${SRC.a1}; 01-secure-business-ai.png`); });
add(async (s,n) => { heading(s,"Secure business AI: a controlled workflow"); flow(s,[{title:"Request and identity",body:"Capture requester, purpose and account scope.",color:C.blue,fill:C.paleBlue},{title:"Restricted runtime",body:"The agent coordinates permitted steps inside set limits.",color:C.blue,fill:C.paleBlue},{title:"Action check",body:"Independent policy checks caller, target and operation.",color:C.teal,fill:C.paleTeal},{title:"Destination evidence",body:"The receiving system records the result.",color:C.navy,fill:C.paleGray}],212,{height:160}); text(s,"Teaching diagram: the proposed action passes through an independent check. Model output cannot grant permission.",{left:92,top:493,width:1000,height:30},{fontSize:19,bold:true,color:C.teal}); footer(s,n); notes(s,"This native teaching diagram elaborates the logical view. The real design must determine which calls can be intercepted, where final enforcement lives, how alternate paths are denied, and how controls reduce misuse within granted permissions.",SRC.a1); });
add(async (s,n) => { heading(s,"Access and action checks"); card(s,"Inputs to evaluate","Caller and represented identity\nResource and operation\nTarget, parameters and destination\nTask context and policy version",{left:92,top:196,width:470,height:294},C.blue,{fill:C.paleBlue}); card(s,"Possible dispositions","Allow a scoped operation\nHold for a valid decision\nDeny with a reason\nCheck returned results before reuse",{left:710,top:196,width:470,height:294},C.teal,{fill:C.paleTeal}); text(s,"A human approval must bind to the exact action. A changed target, amount or destination requires a new decision.",{left:97,top:550,width:1000,height:36},{fontSize:20,bold:true,color:C.navy}); footer(s,n); notes(s,"The action check may represent several services. A content classifier can flag risk, but it cannot expand permissions. The receiving resource still needs a final access check.",SRC.a1); });
add(async (s,n) => { heading(s,"Evidence, holds and recovery"); flow(s,[{title:"Trace",body:"Link task, authorization, resource and result records.",color:C.blue,fill:C.paleBlue},{title:"Verify",body:"Use business-system evidence, not agent narration.",color:C.teal,fill:C.paleTeal},{title:"Stop or revoke",body:"Prevent future work and reconcile in-flight effects.",color:C.amber,fill:C.paleAmber},{title:"Recover",body:"Verify business process and data after restoration.",color:C.navy,fill:C.paleGray}],206,{height:164}); text(s,"Open questions: who decides a hold, what if policy or audit delivery is unavailable, how do rights changes affect queued work, and how is within-permission misuse limited?",{left:92,top:501,width:1070,height:50},{fontSize:18,color:C.red}); footer(s,n); notes(s,"A hold and a denial have different operating meanings. Hold preserves a request for a valid decision or missing prerequisite. Denial terminates a prohibited attempt. Both need evidence and a defined disposition.",SRC.a1); });
add(async (s,n) => { heading(s,"02. Defend against AI"); text(s,"Question: How do we stop attacks that AI helps attackers carry out?",{left:94,top:205,width:1080,height:50},{fontSize:30,bold:true,color:C.navy}); text(s,"AI can make familiar attacker behavior faster or more convincing. Defenses should respond to harmful behavior and business consequence without waiting for proof that AI was involved.",{left:94,top:302,width:1060,height:60},{fontSize:22,color:C.ink}); band(s,"Design focus","Interrupt fraud, compromise, data loss and disruption through control boundaries, evidence and recovery.",450,C.amber); footer(s,n); notes(s,"The architecture does not treat AI as an adversary with intent. It focuses on observable attempts, defensive intervention and verified business recovery.",SRC.a2); });
add(async (s,n) => { heading(s,"Defend against AI","ORIGINAL REFERENCE VISUAL"); await addPng(s,"02-defend-against-ai.png","Defend against AI reference architecture",{left:154,top:154,width:972,height:510}); footer(s,n); notes(s,"Read each row across. Amber represents an attack attempt, teal represents an interrupting boundary, and blue represents a protected asset class. The rows are parallel examples, not a full taxonomy or incident sequence.",`${SRC.a2}; 02-defend-against-ai.png`); });
add(async (s,n) => { heading(s,"Three representative attack paths"); flow(s,[{title:"Impersonation and fraud",body:"Convincing messages and identities can seek a sensitive business change.",color:C.amber,fill:C.paleAmber},{title:"Automated intrusion",body:"Faster discovery and exploitation can expand a compromise path.",color:C.amber,fill:C.paleAmber},{title:"Attacks on AI workflows",body:"Hostile content and tool abuse can redirect a connected workflow.",color:C.amber,fill:C.paleAmber}],220,{height:180}); text(s,"Each path needs a real interruption point. The middle control boundary must produce evidence for investigation and recovery.",{left:96,top:495,width:1000,height:37},{fontSize:20,bold:true,color:C.navy}); footer(s,n); notes(s,"Use MITRE ATT&CK and ATLAS to select scenarios for detailed design. They help name possible behavior; they do not prove local occurrence or control effectiveness.",SRC.a2); });
add(async (s,n) => { heading(s,"Supplier-change impersonation"); flow(s,[{title:"Convincing request",body:"A message, voice or compromised account asks for bank-detail change.",color:C.amber,fill:C.paleAmber},{title:"Independent verification",body:"Use a known contact route and the actual supplier-change approval process.",color:C.teal,fill:C.paleTeal},{title:"Investigate",body:"Correlate request, verification, account, approval and transaction events.",color:C.blue,fill:C.paleBlue},{title:"Contain and reconcile",body:"Revoke access, pause or reconcile a transaction, then verify the supplier record.",color:C.navy,fill:C.paleGray}],210,{height:170}); footer(s,n); notes(s,"The decision does not depend on whether a detector labels a message synthetic. Phishing-resistant sign-in helps protect login but does not substitute for transaction authority and independent business verification.",SRC.a2); });
add(async (s,n) => { heading(s,"Recovery means a usable business service"); card(s,"Containment","Revoke sessions, isolate systems or block harmful transfers under pre-agreed authority.",{left:83,top:190,width:330,height:254},C.teal,{fill:C.paleTeal}); card(s,"Restoration","Restore from protected material and bring the service back through the intended recovery procedure.",{left:474,top:190,width:330,height:254},C.blue,{fill:C.paleBlue}); card(s,"Verification","Check service, data, access state and reconciliation evidence. A rebuilt component is not enough.",{left:865,top:190,width:330,height:254},C.navy,{fill:C.paleGray}); text(s,"Open design question: which response and recovery actions have authority, and how do their decisions feed security telemetry?",{left:92,top:507,width:1060,height:40},{fontSize:19,bold:true,color:C.red}); footer(s,n); notes(s,"The review calls for explicit interfaces between Architecture 02 and Architecture 01 enforcement decisions, including decision telemetry. Recovery must preserve access to response capabilities and recovery material where feasible.",`${SRC.a2}; ${SRC.review}`); });
add(async (s,n) => { heading(s,"03. Defend with AI"); text(s,"Question: How can AI help security act effectively and within limits?",{left:94,top:205,width:1080,height:50},{fontSize:30,bold:true,color:C.navy}); text(s,"AI can help correlate evidence, prioritize work and propose action. Permission, execution and verification require controls beyond a generated answer.",{left:94,top:302,width:1060,height:60},{fontSize:22,color:C.ink}); band(s,"Design focus","Use AI assistance to improve security work while keeping decisions accountable and actions bounded.",450,C.teal); footer(s,n); notes(s,"Security AI itself needs the protections described in Architecture 01: identity, data, tools, runtime, audit and controlled changes. Architecture 03 adds the flow from evidence through verified outcome.",SRC.a3); });
add(async (s,n) => { heading(s,"Defend with AI","ORIGINAL REFERENCE VISUAL"); await addPng(s,"03-defend-with-ai.png","Defend with AI reference architecture",{left:154,top:154,width:972,height:510}); footer(s,n); notes(s,"Read the main flow left to right. The lower path returns tested updates to analysis only; it does not change authorization or execution controls. The dashed analysis boundary is a separation of responsibility, not an enforcement mechanism by itself.",`${SRC.a3}; 03-defend-with-ai.png`); });
add(async (s,n) => { heading(s,"Evidence to verified outcome"); flow(s,[{title:"Security evidence",body:"Source records with provenance, freshness and access limits.",color:C.blue,fill:C.paleBlue,bodySize:16},{title:"AI analysis",body:"Correlate evidence. Show sources and uncertainty.",color:C.blue,fill:C.paleBlue,bodySize:16},{title:"Authorization",body:"Check target, scope, policy and current conditions.",color:C.teal,fill:C.paleTeal,bodySize:16},{title:"Controlled execution",body:"A constrained adapter enforces the operation.",color:C.teal,fill:C.paleTeal,bodySize:16},{title:"Outcome verification",body:"Destination evidence confirms effect or keeps the case open.",color:C.navy,fill:C.paleGray,bodySize:16}],212,{height:160,width:1130,left:75,gap:12}); footer(s,n); notes(s,"The output of analysis is a proposal, not an executable command. Authorization is bound to an operation, target, scope, identity, validity and limits. Verification checks the destination system and service condition.",SRC.a3); });
add(async (s,n) => { heading(s,"Selectable operating modes"); card(s,"Assist","Summarize a case or correlate evidence.\n\nScoped read access. Evidence remains visible. No production action.",{left:82,top:200,width:340,height:270},C.blue,{fill:C.paleBlue}); card(s,"Recommend","Propose a containment or remediation step.\n\nShow evidence, affected assets, consequence and uncertainty for review.",{left:470,top:200,width:340,height:270},C.teal,{fill:C.paleTeal}); card(s,"Act within limits","Execute a tested response inside an authorized procedure.\n\nEnforce target, scope and limits; verify result; allow intervention.",{left:858,top:200,width:340,height:270},C.navy,{fill:C.paleGray}); text(s,"These are operating choices for a use case. They are not a maturity ladder.",{left:92,top:538,width:860,height:32},{fontSize:20,bold:true,color:C.navy}); footer(s,n); notes(s,"Mode selection belongs in the use-case record. A useful analytical result does not authorize later autonomous action.",SRC.a3); });
add(async (s,n) => { heading(s,"Verification, recovery and uncertainty"); flow(s,[{title:"Execution response",body:"The adapter reports what it attempted and received.",color:C.blue,fill:C.paleBlue},{title:"Destination evidence",body:"The receiving system and service health show actual state.",color:C.teal,fill:C.paleTeal},{title:"Uncertain outcome",body:"Conflicting or missing evidence keeps the case open for escalation.",color:C.amber,fill:C.paleAmber},{title:"Recovery decision",body:"An authorized path determines containment, rollback or service recovery.",color:C.navy,fill:C.paleGray}],210,{height:170}); text(s,"Open review finding: recovery and rollback need an explicit authorization path. Execution also needs an accountable identity and delegation model.",{left:92,top:503,width:1080,height:48},{fontSize:18,bold:true,color:C.red}); footer(s,n); notes(s,"Two High findings in the independent review concern recovery/rollback authorization and execution identity/delegation. This deck preserves them as open design questions; it does not claim they are resolved by the logical architecture.",`${SRC.a3}; ${SRC.review}`); });
add(async (s,n) => { heading(s,"Shared interfaces across the three views"); flow(s,[{title:"Authority",body:"Who may permit a specific action, exception or recovery step?",color:C.navy,fill:C.paleGray},{title:"Identity",body:"Which human, workload or delegated identity acts, and within what scope?",color:C.blue,fill:C.paleBlue},{title:"Evidence",body:"Which source records show a decision, attempt, effect and recovery outcome?",color:C.teal,fill:C.paleTeal},{title:"Recovery",body:"Who can stop, contain and restore when normal controls fail?",color:C.amber,fill:C.paleAmber}],210,{height:166}); text(s,"The same event can appear in every view. One implementation owner and clear interfaces avoid duplicated or conflicting controls.",{left:92,top:497,width:1080,height:38},{fontSize:20,bold:true,color:C.navy}); footer(s,n); notes(s,"The overview identifies shared responsibilities. The reviewer asks for a series-level reconciliation of delegated authority, approval records, enforcement telemetry and controlled recovery.",`${SRC.overview}; ${SRC.review}`); });
add(async (s,n) => { heading(s,"Action and approval contract"); question(s,"Action request","Which operation, target, material parameters, intended effect, task and evidence support this request?",198); question(s,"Decision","Which policy version, decision owner, validity conditions and disposition apply?",288,C.teal); question(s,"Approval binding","Can a changed target, amount or destination reuse the approval? It should not.",378,C.amber); question(s,"Execution result","Which destination identifier and reconciliation status show what happened?",468,C.navy); footer(s,n); notes(s,"An architect should model the approval as a record tied to the actual action rather than a narrative summary. Holds and denials also need records that support later investigation and operational disposition.",`${SRC.a1}; ${SRC.a3}`); });
add(async (s,n) => { heading(s,"Execution identity and delegation contract"); card(s,"Initiating identity","Who started the task, and what business purpose and account scope apply?",{left:87,top:220,width:330,height:210},C.blue,{fill:C.paleBlue}); card(s,"Workflow identity","Which non-human identity coordinates the permitted work, and what rights expire?",{left:475,top:220,width:330,height:210},C.teal,{fill:C.paleTeal}); card(s,"Destination identity","Which controlled identity executes the bounded call, and how does the destination verify it?",{left:863,top:220,width:330,height:210},C.navy,{fill:C.paleGray}); text(s,"Open question: how does a delegated child workflow retain task attribution without exceeding the original authority?",{left:93,top:512,width:1060,height:36},{fontSize:19,bold:true,color:C.red}); footer(s,n); notes(s,"Avoid shared unrestricted service identities. A detailed design needs correlation between the initiator, workflow, delegation, authorization artifact and destination execution identity.",`${SRC.a1}; ${SRC.a3}; ${SRC.review}`); });
add(async (s,n) => { heading(s,"Evidence and telemetry contract"); flow(s,[{title:"Source event",body:"Preserve source identity, event time, collection status, classification and retention rule.",color:C.blue,fill:C.paleBlue},{title:"Enforcement decision",body:"Record allow, hold or deny with policy version and reason.",color:C.teal,fill:C.paleTeal},{title:"Execution and outcome",body:"Link destination response, verification evidence, ambiguity and reconciliation status.",color:C.navy,fill:C.paleGray},{title:"Security response",body:"Use the record for investigation, containment, recovery and evidence review.",color:C.amber,fill:C.paleAmber}],210,{height:168}); footer(s,n); notes(s,"Telemetry should include control-boundary decisions as well as assets and detections. The detailed design must decide availability, access, provenance, buffering and loss behavior for evidence.",`${SRC.a1}; ${SRC.a2}; ${SRC.review}`); });
add(async (s,n) => { heading(s,"Supplier payment change through three views"); card(s,"01. Secure business AI","The assistant can read permitted records and prepare the request. It cannot change the payment destination or authority.",{left:74,top:200,width:350,height:276},C.blue,{fill:C.paleBlue}); card(s,"02. Defend against AI","The company verifies the change through a trusted route and investigates suspicious account or transaction activity.",{left:465,top:200,width:350,height:276},C.amber,{fill:C.paleAmber}); card(s,"03. Defend with AI","A security assistant can correlate request, identity and application evidence. Any restriction or recovery action needs authority and verification.",{left:856,top:200,width:350,height:276},C.teal,{fill:C.paleTeal}); footer(s,n); notes(s,"Use this slide to show why one business event needs several architecture perspectives. It is illustrative, and the exact approval, separation-of-duties and recovery process depend on the enterprise.",SRC.overview); });
add(async (s,n) => { heading(s,"Implementation questions"); question(s,"Business consequence","What loss or service impact is unacceptable, and who owns that decision?",185,C.navy); question(s,"Scope","What smallest data access, target and action remain useful for the task?",270,C.blue); question(s,"Authority","Which cases require a human decision, and what binds that decision to the action?",355,C.teal); question(s,"Evidence","Which system can independently show the intended effect and any unintended consequence?",440,C.gray); question(s,"Continuity","What happens when policy, identity, telemetry, model, tool adapter or destination system is unavailable?",525,C.amber); footer(s,n); notes(s,"These questions turn a logical reference into detailed architecture work. The architecture does not supply universal thresholds, assigned owners or product selections.",`${SRC.a1}; ${SRC.a2}; ${SRC.a3}`); });
add(async (s,n) => { heading(s,"From logical view to deployment design"); flow(s,[{title:"Choose one use case",body:"Name the business or security task, outcome, affected systems and prohibited actions.",color:C.navy,fill:C.paleGray},{title:"Map real interfaces",body:"Identify data, identity, policies, tools, destinations, evidence and recovery dependencies.",color:C.blue,fill:C.paleBlue},{title:"Define operating envelope",body:"Select assistance mode, action limits, approval points, stops and fallback.",color:C.teal,fill:C.paleTeal},{title:"Test and decide",body:"Run representative and hostile cases, verify outcomes, then seek accountable acceptance.",color:C.amber,fill:C.paleAmber}],210,{height:170}); footer(s,n); notes(s,"This is a design sequence, not an adoption timeline. A real deployment needs its own security, business, privacy, continuity and change decisions.",`${SRC.standard}; ${SRC.a3}`); });
add(async (s,n) => { heading(s,"Testable acceptance checks"); card(s,"Hostile-content resistance","Insert a malicious instruction in test evidence. Confirm it cannot change policy, expand scope or trigger an unauthorized action.",{left:82,top:170,width:348,height:270},C.amber,{fill:C.paleAmber,bodySize:17}); card(s,"Independent authorization","Attempt an altered or model-generated action directly. Confirm controlled execution rejects it without a bounded authorization.",{left:466,top:170,width:348,height:270},C.teal,{fill:C.paleTeal,bodySize:17}); card(s,"Verification and continuity","Simulate ambiguous result, policy failure and AI outage. Confirm the case stays open and people can follow the non-AI procedure.",{left:850,top:170,width:348,height:270},C.navy,{fill:C.paleGray,bodySize:17}); text(s,"Acceptance evidence should trace source evidence, proposal, authorization, execution, verification and disposition.",{left:92,top:506,width:1070,height:36},{fontSize:20,bold:true,color:C.navy}); footer(s,n); notes(s,"These are example acceptance checks to adapt to business consequence and technical behavior. Passing a test does not create general assurance outside the tested scope. Within-permission misuse remains a design question for task constraints and review.",`${SRC.a1}; ${SRC.a2}; ${SRC.a3}`); });
add(async (s,n) => { heading(s,"Model-assisted review: open findings"); card(s,"What the review observed","Fable 5.1 found useful authority separation and discussion-level architect use. It also noted a spelling error in the original 03 PNG.",{left:80,top:200,width:490,height:250},C.teal,{fill:C.paleTeal,bodySize:18}); card(s,"What remains open","The review raised 30 findings. Mechanical public corrections were made; substantive design questions remain open. Human review remains open.",{left:710,top:200,width:490,height:250},C.red,{fill:C.paleRed,bodySize:18}); text(s,"The next revision should triage findings, decide which changes need canonical source updates, and preserve the frozen reviewed packages.",{left:92,top:532,width:1060,height:38},{fontSize:19,bold:true,color:C.navy}); footer(s,n); notes(s,"This slide summarizes the Fable 5.1 review of the original packages. A separate bounded model-assisted review covered the revised overview and governance companion. Neither is an acceptance decision, deployment-ready certification, or human review.",SRC.review); });
add(async (s,n) => { heading(s,"Material design questions to resolve"); question(s,"Recovery authorization","Who may invoke rollback, containment or restoration, under which bounded conditions?",188,C.red); question(s,"Execution identity","Which accountable identity acts at the destination, and how is delegation traceable?",276,C.red); question(s,"Approval binding","How does a human view and approve the exact target, scope and material parameters?",364,C.red); question(s,"Enforcement telemetry","How do allow, hold and deny decisions enter the evidence and investigation path?",452,C.red); question(s,"AI unavailable or manipulated","How do people continue essential work and retain authority when AI assistance cannot be trusted?",540,C.red); footer(s,n); notes(s,"These questions include the two High Architecture 03 review findings and the cross-architecture interface work named in the review summary. They remain open for detailed design and owner decision.",SRC.review); });
add(async (s,n) => { heading(s,"Limits of the reference series"); card(s,"Logical, not physical","A box may map to several services. The diagrams do not prescribe topology, product or network placement.",{left:80,top:175,width:350,height:270},C.blue,{fill:C.paleBlue}); card(s,"Cybersecurity scope","The series connects to privacy, safety and business-quality issues without claiming to cover them.",{left:465,top:175,width:350,height:270},C.teal,{fill:C.paleTeal}); card(s,"Evidence before confidence","A model explanation, tool acknowledgement or favorable demonstration does not establish local effectiveness.",{left:850,top:175,width:350,height:270},C.navy,{fill:C.paleGray}); footer(s,n); notes(s,"Restate the practical boundary: technical authorization can still lead to an inaccurate, inappropriate or harmful business action. Business purpose and consequences inform the controls.",SRC.overview); });
add(async (s,n) => { heading(s,"Appendix: terms used in this deck"); question(s,"Authorization","Deciding whether an identity may perform an action on a target in the current context.",180,C.blue); question(s,"Non-human identity","An identity assigned to an application or automated workflow.",258,C.blue); question(s,"Prompt injection","Untrusted content that tries to redirect an AI workflow or misuse its permitted access.",336,C.amber); question(s,"Provenance","Where information came from and how it was obtained.",414,C.gray); question(s,"Autonomy limit","Actions a workflow may take without a new human decision.",492,C.teal); footer(s,n); notes(s,"Use plain language first. These definitions help readers connect ordinary security practice to the architecture vocabulary.",SRC.standard); });
add(async (s,n) => { heading(s,"Source basis"); text(s,"This series synthesizes proposed architecture patterns from its canonical Markdown and guides. The primary sources below inform risk selection and questions; they do not approve the design.",{left:92,top:172,width:1060,height:52},{fontSize:21,color:C.ink}); const sourceText="NIST Cyber AI Profile project\nMITRE ATT&CK and ATLAS\nNCSC guidance on agentic AI and Cyber Shield\nOWASP GenAI LLM Top 10 and Agentic Applications Top 10\nCISA guidance on phishing-resistant MFA"; text(s,sourceText,{left:120,top:275,width:1040,height:190},{fontSize:22,color:C.navy}); text(s,"Complete links and source-status notes appear in the canonical Markdown and detailed guides.",{left:96,top:535,width:1050,height:32},{fontSize:19,color:C.gray}); footer(s,n); notes(s,"The canonical sources identify the date and status of each source. Examples and component arrangements in this deck are a proposed synthesis rather than a NIST, MITRE, NCSC, OWASP or CISA reference architecture.",`${SRC.overview}; ${SRC.a1}; ${SRC.a2}; ${SRC.a3}`); });
add(async (s,n) => { heading(s,"Discussion guide"); text(s,"A useful next conversation starts with one workflow or security task.",{left:94,top:188,width:1000,height:50},{fontSize:29,bold:true,color:C.navy}); question(s,"1","What outcome must the workflow or response protect?",290,C.blue); question(s,"2","What may the AI read, propose or do, and where does a person decide?",370,C.teal); question(s,"3","What source evidence verifies the action and supports recovery if it goes wrong?",450,C.amber); text(s,"Use the detailed guides to prepare the architecture, evidence and owner decisions for that single use case.",{left:94,top:558,width:1080,height:35},{fontSize:20,color:C.ink}); footer(s,n); notes(s,"Close by moving from the reference series to a bounded, accountable design conversation. No deployment decision follows from this deck alone.",`${SRC.overview}; ${SRC.standard}`); });

for (let i = 0; i < slides.length; i += 1) {
  const slide = deck.slides.add();
  slide.background.fill = C.white;
  await slides[i](slide, i + 1);
}

const candidatePath = path.join(tmpDir, "ai-security-reference-architectures.candidate.pptx");
await (await PresentationFile.exportPptx(deck)).save(candidatePath);
console.log(JSON.stringify({ candidatePath, slides: slides.length, font }, null, 2));
